wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717209480
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 105
      3:
      - 13
      - 23
      4: 3.12.3
      5: 0.17.0
      6: 4.41.2
      8:
      - 5
      13: linux-x86_64
